### ISSUE TITLE
Remove unnecessary country / language parameter

### ISSUE THREAD

**Issue by deftdawg** [etheralm/libpurecool#14]
I'm not sure if it was required for login at some point in the past, however the APIs can be accessed without the need of a country or language code.   It's not necessary, it's incompletely documented in home-assistant (downstream) and a source of red herrings when attempting to troubleshoot issues with why Dyson's can't be connected.

Here is a shell script that uses curl to hit the APIs without the language parameter, that I put together in trying to understand why my setup gives me a ``OSError: [Errno 113] Host is unreachable`` when using invoking libpurecool from home-assistant:

https://gist.github.com/deftdawg/11a0b46fc44c5764acb6730431006a02

**Comment by etheralm** [comment]
The mobile apps submit the language parameter with the API call, that's the reason why it is in the library too. It is poorly documented downstream in the hass integration, because there is no official documentation from dyson for their API. That said I also never noticed a difference when using different language codes and it may be unnecessary, but someone has to also test such a change with accounts created from other countries  and I also very recently merged a PR that uses a different base url for Chinese accounts based on the language string, see: https://github.com/etheralm/libpurecool/pull/13

The call to the dyson API is only used for authentication and to fetch a list of devices registered to the dyson account, then the library connects directly to the devices using MQTT. It may be quite possible that you are getting this error because the library can't reach your device from your hass instance. If you are having issues with the home assistant integration you can open an issue there and I'll try to help.

**Comment by etheralm** [comment]
I forgot to mention that I'm also currently looking into updating the dyson integration in hass with support for auto discovery and the config flow, which will allow you to configure the fan from the web ui and will probably present the language string as a dropdown, which would hopefully remove a lot of the confusion around the configuration.
